name: Visitors Count
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-visitors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Profile Views Counter
        uses: antonkomarev/github-profile-views-counter@1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
